{
    "requestNo" : "10002" ,
    "patientId" : "test" ,
    "generatedBy" : "test" ,
    "consultationNote":[{
    "consultationNo" : "test" ,
    "date" : "test" ,
    "description" : "test" ,
    "consultationNotes" : "test" ,
    "doctorNotes" : "test" ,
    "audioNotes" : "test" ,
    "status" : "test" ,
    "speciality" : "test" ,
    "specialist" : "test" ,
    "requester" : "test" ,
    "completedTime" : "test"}] ,
    "residentNotes":[{"residentNoteNo" : "test" ,
    "date" : "test" ,
    "description" : "test" ,
    "doctor" : "test" ,
    "note" : "test" ,
    "status" : "test" ,
    "section" : "test" ,
    "audioNotes" : "test" ,
    "code" : ["test"] }],
    "pharmacyRequest":[{"ReplenishmentRequestBuID" : "test"}] ,
    "labRequest":[{"lRrequestNo" : "test" ,
    "serviceId" : "test" ,
    "price" : "test" ,
    "requesterName" : "test" ,
    "serviceCode" : "test" ,
    "serviceName" : "test" ,
    "status" : "test" ,
    "requester" : "test" ,
    "results" : "test" ,
    "sampleId" : "test" ,
    "comments" : "test" ,
    "serviceType" : "test" ,
    "activeDate" : "test" ,
    "completedDate" : "test" ,
    "date" : "test"}] ,
    "radiologyRequest":[{"rRrequestNo" : "test" ,
    "serviceId" : "test" ,
    "price" : "test" ,
    "serviceCode" : "test" ,
    "status" : "test" ,
    "requesterName" : "test" ,
    "serviceName" : "test" ,
    "requester" : "test" ,
    "results" : "test" ,
    "comments" : "test" ,
    "serviceType" : "test" ,
    "consultationNote" : "test" ,
    "activeDate" : "test" ,
    "completedDate" : "test" ,
    "date" : "test"}] ,
    "nurseService":[{"NSrequestNo" : "test" ,
    "serviceId" : "test" ,
    "price" : "test" ,
    "requesterName" : "test" ,
    "serviceCode" : "test" ,
    "status" : "test" ,
    "serviceName" : "test" ,
    "comments" : "test" ,
    "requester" : "test" ,
    "date" : "test"}] ,
    "dischargeRequest":{
        "dischargeSummary":{"dischargeNotes" : "nhbgdfv",
    "otherNotes" : "ngfbg"},
    "dischargeMedication":{
    "date" : "c",
    "status" : "c",
    "requester" : "c",
    "medicine":[{"itemId" : "nbg",
    "priority" : "tenhfbg",
    "schedule" : "ynhgbfv",
    "dosage" : "tuyhrtgef",
    "frequency" : "qwert",
    "duration" : "nbvc",
    "requestedQty" : "nhfbgdv",
    "medicineName" : "hmnbgfv",
    "unitPrice" : "jgnhfbgv",
    "totalPrice" : "jgmnhfbgdv",
    "itemType" : "jhmnbfv",
    "make_model" : "mnbfgdcx",
    "size" : "jhnbgf"}]},
    "status" : "vdssdb",
    "inProcessDate" : "dgfvsd",
    "completionDate" : "vdsc"},
    "status" : "vdssdb",
    "triageAssessment":[{"status" : "test" ,
    "reason" : "test" ,
    "triageRequestNo" : "test" ,
    "heartRate" : "test" ,
    "bloodPressureSys" : "test" ,
    "bloodPressureDia" : "test" ,
    "respiratoryRate" : "test" ,
    "temperature" : "test" ,
    "FSBS" : "test" ,
    "painScale" : "test" ,
    "pulseOX" : "test" ,
    "triageLevel" : ["test"] ,
    "generalAppearance" :["test"] ,
    "headNeck" : ["test"] ,
    "respiratory" : ["test"] ,
    "cardiac" : ["test"] ,
    "abdomen" : ["test"] ,
    "neurological" : ["test"] ,
    "requester" : "test" ,
    "date" : "test" }],
    "followUp":[{"requester" : "test" ,
    "approvalNumber" : "test" ,
    "approvalPerson" : "test" ,
    "file" : "test" ,
    "description" : "test" ,
    "notes" : "test" ,
    "status" : "test" ,
    "doctorName" : "test" ,
    "doctor" : "test" ,
    "date" : "test"}] ,
    "requestType" : "test" ,
    "functionalUnit" : "test" ,
    "verified" : "test" ,
    "insurerId" : "test" ,
    "paymentMethod" : "test" ,
    "claimed" : "test" ,
    "createdAt" : "test" ,
    "updatedAt": "test"
    }